### ISSUE TITLE
generate fr and de - 169

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/cloud-manager-family#20]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by ntap-bmegan** [comment]
@netapp-bcammett - Why is localization disabled for this repo? Others are localized. For example, Astra: 

https://github.com/NetAppDocs/astra-family/blob/main/project.yml

**Comment by ntap-bmegan** [comment]
@netapp-bcammett - Follow-up. This was previously localized but at some point it was disabled. Why is that?

https://github.com/orgs/NetAppDocs/repositories?q=cloud-manager-family&type=all&language=&sort=

**Comment by netapp-bcammett** [comment]
I have no idea. I don't even know how to disable localization. I see no reason why it shouldn't be localized.

**Comment by ntap-bmegan** [comment]
@netapp-bcammett - I don't find a commit where the necessary setting was present so I'm not sure how it got localized before. Now it's the lack of a `harmony_enabled` keyword that's the problem. But I'm seeing inconsistent project.yml files across families, so I'll review them and get back to you.

**Comment by ntap-bmegan** [comment]
@netapp-bcammett - I've reviewed the other family repos and will recommend the `internal` and `prod` subsections shown below for any that don't already have them. 

````
settings:
  name: BlueXP
  platform: cloud
  search: # values omitted for brevity
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true 
````

If you add them now, that should generate the expected French and German sites. You don't need to coordinate anything in advance. Just tag this issue when you're done.
